### PR TITLE
Add Server::isCli

### PR DESCRIPTION
**Pull request by distantnative**
Or probably rather include in nem Kirby\Environment package

### CODE REVIEW

**Comment by distantnative** [comment]
@bastianallgeier Rather have that in the Environment package?

**Comment by bastianallgeier** [comment]
Yes, makes much more sense!

**Comment by bastianallgeier** [comment]
In fact I think the Server class should be part of HTTP.

**Comment by distantnative** [comment]
Moving Server class to Http: https://github.com/k-next/http/pull/26

**Comment by bastianallgeier** [comment]
This can be closed now, right?

**Pull request closed without merging**
