### PR TITLE
Better internationalized domain name support

### PR DESCRIPTION
**Pull request by distantnative**
Better internationalized domain name support

- url::idn() now converts full URLs, not only domain names
- Add url::unIdn()

v2 port of https://github.com/getkirby/toolkit/commit/dc320a34227190acc72bad9840838ba51aa323b9

### CODE REVIEW

**Comment by distantnative** [comment]
@lukasbestle @bastianallgeier I am a bit stuck here – how could we test this in a good way without knowing whether the functions are actually available?

**Comment by lukasbestle** [comment]
To be honest I'm not sure either, especially because of https://github.com/getkirby/toolkit/issues/251. We can't really rely on the IDN methods to be available and to work.

Maybe we should be using a [library like this one (haven't reviewed this yet)](https://github.com/true/php-punycode) instead? That's probably much more reliable on our customers' servers as it works the same everywhere.

**Comment by distantnative** [comment]
I agree. Trying to write passable tests here just feels more and more like cheating ourselves.

**Comment by lukasbestle** [comment]
Another issue with IDN support in v2: Kirby repo, PR 608 (not linked to avoid creating a back-reference). The issue is the deprecated default variant param `INTL_IDNA_VARIANT_2003` in PHP 7.2. We should definitely consider switching to a user-space library now, the built-in ones aren't stable at all...

**Pull request closed without merging**
